#!/usr/bin/env bash
# =============================================================================
# setup_runpod.sh — One-shot RunPod environment setup
#
# Run this script once after SSHing into the pod.
# Required env vars (set in RunPod pod config before launching):
#   S3_ACCESS_KEY     — RunPod S3 access key
#   S3_SECRET_KEY     — RunPod S3 secret key
#   BUCKET_NAME       — RunPod S3 bucket name
#   HF_TOKEN          — HuggingFace token (optional, for private models)
#   WANDB_API_KEY     — W&B key (optional, set "none" to disable)
#
# Usage (from /workspace/kabyle-speech-recognition):
#   bash setup_runpod.sh
# =============================================================================
set -euo pipefail

# ─── Paths ────────────────────────────────────────────────────────────────────
WORKSPACE="/workspace"
REPO_DIR="$WORKSPACE/kabyle-speech-recognition"
DATA_DIR="$REPO_DIR/data/raw"
ARCHIVE_NAME="Kabyle-DS.tar.gz"
EXTRACTED_DIR="cv-corpus-25.0-2026-03-09"
S3_ENDPOINT="https://s3api-us-ca-2.runpod.io"
BUCKET="${BUCKET_NAME:-}"

echo "================================================================"
echo " Kabyle Speech Recognition — RunPod Setup"
echo "================================================================"

# ─── 1. CUDA torch ────────────────────────────────────────────────────────────
echo ""
echo "[1/5] Checking PyTorch + CUDA..."
if python -c "import torch; assert torch.cuda.is_available(), 'No CUDA'" 2>/dev/null; then
    echo "      PyTorch with CUDA already available — skipping."
else
    echo "      Installing PyTorch with CUDA 12.1..."
    pip install --quiet torch torchvision torchaudio \
        --index-url https://download.pytorch.org/whl/cu121
fi

# ─── 2. Project dependencies ──────────────────────────────────────────────────
echo ""
echo "[2/5] Installing project dependencies..."
pip install --quiet \
    transformers>=4.36.0 \
    datasets>=2.16.0 \
    accelerate>=0.25.0 \
    jiwer>=3.0.0 \
    librosa>=0.10.0 \
    soundfile>=0.12.0 \
    peft>=0.7.0 \
    bitsandbytes>=0.41.0 \
    wandb>=0.16.0 \
    tensorboard>=2.15.0 \
    pyyaml>=6.0 \
    python-dotenv>=1.0.0 \
    tqdm>=4.66.0

# Install the project package itself (makes src/ importable)
pip install --quiet -e "$REPO_DIR" --no-deps
echo "      Done."

# ─── 3. (S3 download skipped — dataset uploaded directly via scp) ─────────────
echo ""
echo "[3/5] Skipping S3 download — expecting dataset already on volume via scp."

# ─── 4. Extract dataset ───────────────────────────────────────────────────────
echo ""
echo "[4/5] Dataset..."
mkdir -p "$DATA_DIR"

# Move archive from /workspace root if scp'd there
if [ -f "$WORKSPACE/$ARCHIVE_NAME" ] && [ ! -f "$DATA_DIR/$ARCHIVE_NAME" ]; then
    echo "      Moving archive from $WORKSPACE to $DATA_DIR..."
    mv "$WORKSPACE/$ARCHIVE_NAME" "$DATA_DIR/$ARCHIVE_NAME"
fi

if [ ! -f "$DATA_DIR/$ARCHIVE_NAME" ]; then
    echo "ERROR: Archive not found at $DATA_DIR/$ARCHIVE_NAME"
    echo "       scp it to the pod first:"
    echo "       scp -i ~/.ssh/id_ed25519 Kabyle-DS.tar.gz <user>@ssh.runpod.io:/workspace/"
    exit 1
fi

if [ ! -d "$DATA_DIR/$EXTRACTED_DIR" ]; then
    echo "      Extracting archive (~17 GiB, takes a few minutes)..."
    tar -xzf "$DATA_DIR/$ARCHIVE_NAME" -C "$DATA_DIR"
    echo "      Extracted to $DATA_DIR/$EXTRACTED_DIR"
else
    echo "      Dataset already extracted — skipping."
fi

# ─── 5. Write RunPod .env ─────────────────────────────────────────────────────
echo ""
echo "[5/5] Writing .env..."
cat > "$REPO_DIR/.env" <<EOF
# RunPod environment — generated by setup_runpod.sh
HF_TOKEN=${HF_TOKEN:-}
WANDB_API_KEY=${WANDB_API_KEY:-none}
CUDA_VISIBLE_DEVICES=0
NUM_WORKERS=4
DATASETS_AUDIO_BACKEND=soundfile
# Full dataset — no MAX_TRAIN_SAMPLES / MAX_EVAL_SAMPLES limits
EOF
echo "      .env written."

# ─── Done ─────────────────────────────────────────────────────────────────────
echo ""
echo "================================================================"
echo " Setup complete!"
echo ""
echo " Verify GPU:"
echo "   python -c \"import torch; print(torch.cuda.get_device_name(0))\""
echo ""
echo " Run baseline eval (large-v3 zero-shot, ~30 min on A100):"
echo "   cd $REPO_DIR"
echo "   python scripts/baseline_eval.py --config configs/whisper_large_lora.yaml"
echo ""
echo " Run full LoRA fine-tuning:"
echo "   cd $REPO_DIR"
echo "   python scripts/run_pipeline.py --config configs/whisper_large_lora.yaml"
echo "================================================================"
